---
apiVersion: kubevirt.io/v1
metadata:
  labels:
    special: vm-per
  name: vm-per
kind: VirtualMachine
spec:
  running: false
  template:
    metadata:
      labels:
        kubevirt.io/vm: vm-fedora-persist
    spec:
      networks:
      - name: default
        pod: {}
      domain:
        devices:
          interfaces:
            - name: default
              masquerade: {}
          disks:
          - disk:
              bus: virtio
            name: datavolumedisk1
          - disk:
              bus: virtio
            name: cloudinitdisk
          rng: {}
        machine:
          type: ""
        resources:
          requests:
            memory: 2048M 
      terminationGracePeriodSeconds: 0
      volumes:
        - dataVolume:
            name: fedora-persist-dv
          name: datavolumedisk1
        - cloudInitNoCloud:
            userData: |
              #cloud-config
              hostname: fedora-0
              password: fedora
              chpasswd: { expire: False }
              ssh_pwauth: True
              disable_root: false
              # Place your ssh public key here
              #ssh_authorized_keys:
              #  - ssh-rsa ...
          name: cloudinitdisk
  dataVolumeTemplates:
    - metadata:
        name: fedora-persist-dv
      spec:
        pvc:
          storageClassName: gp3-csi
          accessModes:
          - ReadWriteMany
          resources:
            requests:
              storage: 5Gi
        source:
          registry: 
            url: docker://quay.io/kubevirt/fedora-cloud-container-disk-demo